### ISSUE TITLE
Linux Version or kernel version requirement?

### ISSUE THREAD

**Issue by wz8530** [deghat-farhad/Arch-linux-on-GU603H-ROG-zephyrus-M16-#1]
Can you tell me what the Linux version or kernel version requirements are? my Linux system is Ubuntu 20.04.5, and the kernel is 5.15.0-50.

**Comment by deghat-farhad** [comment]
currently, I'm using `5.19.12-arch1-1`.

**Comment by wz8530** [comment]
thanks！
